"""Initial Sprint 1 migration

Revision ID: 646ffecdf2ed
Revises:
Create Date: 2026-03-22 00:16:09.569696

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '646ffecdf2ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_intelligence',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('coordination_patterns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('temporal_anomalies', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_scores', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence_patterns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('group_anomalies', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cross_video_timeline', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_text', sa.String(), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('pattern_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_intelligence_case_id'), 'case_intelligence', ['case_id'], unique=True)
    op.create_table('video_files',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('processed_frames', sa.Integer(), nullable=False),
    sa.Column('entity_count_discovered', sa.Integer(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_files_case_id'), 'video_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_video_files_status'), 'video_files', ['status'], unique=False)
    op.create_table('negative_match_pairs',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('entity_a_id', sa.String(length=36), nullable=False),
    sa.Column('entity_b_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negative_match_pairs_case_id'), 'negative_match_pairs', ['case_id'], unique=False)
    op.create_table('pending_matches',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('entity_a_id', sa.String(length=36), nullable=False),
    sa.Column('entity_b_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_matches_case_id'), 'pending_matches', ['case_id'], unique=False)
    op.create_index(op.f('ix_pending_matches_entity_a_id'), 'pending_matches', ['entity_a_id'], unique=False)
    op.create_index(op.f('ix_pending_matches_entity_b_id'), 'pending_matches', ['entity_b_id'], unique=False)
    op.create_index(op.f('ix_pending_matches_status'), 'pending_matches', ['status'], unique=False)
    op.create_foreign_key(None, 'behavior_records', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'case_evidence', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'case_notes', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detections', 'entities', ['entity_id'], ['id'], ondelete='SET NULL')
    op.add_column('entities', sa.Column('case_id', sa.String(length=36), nullable=True))
    op.add_column('entities', sa.Column('video_file_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_entities_video_file_id'), 'entities', ['video_file_id'], unique=False)
    op.create_foreign_key(None, 'entities', 'video_files', ['video_file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'entities', 'cases', ['case_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'entity_profiles', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sightings', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'temporal_events', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temporal_events', type_='foreignkey')
    op.drop_constraint(None, 'sightings', type_='foreignkey')
    op.drop_constraint(None, 'entity_profiles', type_='foreignkey')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_index(op.f('ix_entities_video_file_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_column('entities', 'video_file_id')
    op.drop_column('entities', 'case_id')
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_constraint(None, 'case_notes', type_='foreignkey')
    op.drop_constraint(None, 'case_evidence', type_='foreignkey')
    op.drop_constraint(None, 'behavior_records', type_='foreignkey')
    op.drop_index(op.f('ix_pending_matches_status'), table_name='pending_matches')
    op.drop_index(op.f('ix_pending_matches_entity_b_id'), table_name='pending_matches')
    op.drop_index(op.f('ix_pending_matches_entity_a_id'), table_name='pending_matches')
    op.drop_index(op.f('ix_pending_matches_case_id'), table_name='pending_matches')
    op.drop_table('pending_matches')
    op.drop_index(op.f('ix_negative_match_pairs_case_id'), table_name='negative_match_pairs')
    op.drop_table('negative_match_pairs')
    op.drop_index(op.f('ix_video_files_status'), table_name='video_files')
    op.drop_index(op.f('ix_video_files_case_id'), table_name='video_files')
    op.drop_table('video_files')
    op.drop_index(op.f('ix_case_intelligence_case_id'), table_name='case_intelligence')
    op.drop_table('case_intelligence')
    # ### end Alembic commands ###
